#!/usr/bin/env perl

use warnings;
use strict;
use autodie qw(:all);

my $version = shift or die "no version";

`git rm gumbo-*.tar.gz`;
`git submodule foreach git checkout $version`;
`git commit -m "Update gumbo source to $version" gumbo-src`;
`cd gumbo-src; ./autogen.sh && ./configure && make dist`;
`mv gumbo-src/gumbo-*.tar.gz .`;
`git add gumbo-*.tar.gz`;
`./Build manifest`;
`git add MANIFEST`;
`git commit -m "Update gumbo tarball to $version" gumbo-* MANIFEST`;
